### ISSUE TITLE
arguments slice

### ISSUE THREAD

**Issue by fanatid** [paulmillr/micro-promisify#1]
[leaking arguments](https://github.com/paulmillr/micro-promisify/blob/b158fedb0b2da1e504660ddcb6ca79ffd050d23d/index.js#L3) is one of the [optimization killers](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments)

**Comment by paulmillr** [comment]
good point.

**Comment by fanatid** [comment]
@paulmillr do you have plans on implementing `micro-promisify-all`?
OOI, what code style are you using?

**Comment by paulmillr** [comment]
Here's a four-liner for `promisifyAll`:

```javascript
promisifyAll = (obj) => Object.keys(obj).reduce((bound, key) => {
  bound[key] = promisify(obj[key]).bind(obj);
  return bound;
}, {});
```

I generally don't like the idea of importing the whole module. Instead, it's more concise to specify individual functions you're importing. For example you might need only `readFile` from `fs`, or 5 other functions instead of 25+ it does have.

Code style: https://github.com/paulmillr/code-style-guides#javascript
